### ISSUE TITLE
enable-suggest option not work

### ISSUE THREAD

**Issue by o-matsuo** [codelibs/fess-site-search#105]
i use FSS.
but enable-suggest option not work.

setAttribute
     fess-url: http://localhost:8080/json

i called this url
    fss site: http://localhost/fss/  <-- virtual host

chrom error message: 
 fess-ss.min.js:24 Cross-Origin Read Blocking (CORB) blocked cross-origin response <<url/suggest?callback=....>>
 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by marevol** [comment]
What Fess version do you use?

**Comment by o-matsuo** [comment]
sorry.

fess version: 13.2.0
elasticsearch version: 7.2.0
jdk version: openjdk11.0.3_7

**Comment by ozgengures** [comment]
hi @o-matsuo 

i solved this problem with changing this line `dataType: "jsonp",`  to `dataType: "json",` [suggestor.js](https://github.com/codelibs/fess-site-search/blob/bcbd62148b57b01ca04bc21b383875e56c5369c6/fss/src/12.7/suggestor.js#L110)

maybe @marevol  or @yfujita should new release with this fix.

**Comment by yfujita** [comment]
@o-matsuo @ozgengures 
I couldn't reproduce this problem, but api of fess13 must be requested with `dataType: "json"`.
I fixed this problem and released . Please use new version of FSS.
